% Load settings from prior simulations
theData = load('\Users\deena\Dropbox (Aguirre-Brainard Lab)\MELA_datadev\Experiments\ForcedChoiceCM\OLRayleighMatch\paramsSearch\varyNoiseForPaper2_0_FC\varyNoiseForPaper2_0_FC_paramsSearchData.mat');
testWls = theData.test;

% Conduct Rayleigh matching simulations with a single test wavelength, and
% attempt to recover the parameters.
subjID = 'testStaircaseSingleRef';
coneAvgErr = zeros(1,length(testWls)+1);
coneAvgStdErr = zeros(1,length(testWls)+1);

for i = 1:length(testWls)
    [coneAvgErr(i),~,coneAvgStdErr(i)] = ...
        sampleRayleighMatch([subjID '_' num2str(i)],20,zeros(1,8),[0 0 1 1 0 1 1 0],...
        theData.opponentParams,theData.p1,theData.p2,testWls(i),'forcedChoice',...
        'nObserverMatches',theData.p.Results.nObserverMatches,'nReversals',...
        theData.p.Results.nReversals,'age',theData.p.Results.age,...
        'p1Scale',theData.p.Results.p1Scale,'p2Scale',theData.p.Results.p2Scale,...
        'testScale',theData.p.Results.testScale,'LMEqualOD',...
        theData.p.Results.LMEqualOD, 'dlens0',theData.p.Results.dlens0,...
        'restrictBySd',theData.p.Results.restrictBySd,'dmac0',...
        theData.p.Results.dmac0,'adjustmentLength',theData.p.Results.adjustmentLength,...
        'sampledObservers',theData.p.Results.sampledObservers,...
        'noiseScaleFactor',theData.p.Results.noiseScaleFactor,'fieldSize',...
        theData.p.Results.fieldSize,'errWls',[],'stimLimits',...
        [],'lambdaRef',[],'makeNoObserverPlots',true);
end

% Combined session
[coneAvgErr(length(testWls)+1),~,coneAvgStdErr(length(testWls)+1)] = ...
    sampleRayleighMatch([subjID '_' num2str(length(testWls)+1)],20,...
    zeros(1,8),[0 0 1 1 0 1 1 0],...
    theData.opponentParams,theData.p1,theData.p2,testWls,'forcedChoice',...
    'nObserverMatches',theData.p.Results.nObserverMatches,'nReversals',...
    theData.p.Results.nReversals,'age',theData.p.Results.age,...
    'p1Scale',theData.p.Results.p1Scale,'p2Scale',theData.p.Results.p2Scale,...
    'testScale',theData.p.Results.testScale,'LMEqualOD',...
    theData.p.Results.LMEqualOD, 'dlens0',theData.p.Results.dlens0,...
    'restrictBySd',theData.p.Results.restrictBySd,'dmac0',...
    theData.p.Results.dmac0,'adjustmentLength',theData.p.Results.adjustmentLength,...
    'sampledObservers',theData.p.Results.sampledObservers,...
    'noiseScaleFactor',theData.p.Results.noiseScaleFactor,'fieldSize',...
    theData.p.Results.fieldSize,'errWls',[],'stimLimits',...
    [],'lambdaRef',[],'makeNoObserverPlots',true);