function [coneErrStaircase,coneErrQuest,coneErrStd] = ...
    compareQuestStaircaseRayleigh(subjID,p1Wl,p2Wl,testWls,...
    baseConeParams,coneParamsToVary,nObservers,...
    nQuestTrials,method,noiseScaleFactor,varargin)
%% Setup
% Parse input 
p = inputParser;
p.addParameter('precomputeQuest',false,@(x)(islogical(x)));
p.addParameter('age',32,@(x)(isnumeric(x)));
p.addParameter('fieldSize',2,@(x)(isnumeric(x)));
p.addParameter('opponentParams',[0.8078 4.1146 1.2592 0.0200],@(x)(isvector(x)));
p.addParameter('p1Scale',1,@(x)(isnumeric(x)));
p.addParameter('p2Scale',0.02,@(x)(isnumeric(x)));
p.addParameter('testScale',0.5,@(x)(isnumeric(x)));
p.addParameter('lambdaRef',0.8,@(x)(isnumeric(x)));
p.addParameter('S',[400 1 301],@(x)(isnumeric(x)));
p.addParameter('adjustmentLength',3201,@(x)(isnumeric(x)));
p.addParameter('nObserverMatches',1,@(x)(isnumeric(x)));
p.addParameter('nReversals',[1 4],@(x)(isnumeric(x)));
p.addParameter('nBelowThreshold',1,@(x)(isnumeric(x)));
p.addParameter('thresholdScaleFactor',0.5,@(x)(isnumeric(x)));
p.parse(varargin{:});

% Define output directory 
outputDir = fullfile(getpref('ForcedChoiceCM','rayleighDataDir'),...
    'Quest',subjID);
if (~exist(outputDir,'dir'))
    mkdir(outputDir);
end
fName = [subjID '_StaircaseQuestComparison.mat'];
outputFile = fullfile(outputDir,fName);


% Get cone parameters for the simulated observers.
sampledConeParams = sampleRayleighObservers(nObservers,baseConeParams,...
    coneParamsToVary);

%% Staircase
% Generate monochromatic spectra
wls = SToWls(p.Results.S);

% Run the test
[~,~,~,~,~,~,recoveredStaircaseParams]...
    = sampleRayleighMatch(subjID,nObservers,baseConeParams,coneParamsToVary,...
    p.Results.opponentParams,p1Wl,p2Wl,testWls,method,'age',p.Results.age,...
    'fieldSize',p.Results.fieldSize,'monochromatic',true,...
    'p1Scale',p.Results.p1Scale,'p2Scale',p.Results.p2Scale,'testScale',...
    p.Results.testScale,'S',p.Results.S,'adjustmentLength',...
    p.Results.adjustmentLength,'nReversals',p.Results.nReversals,...
    'nObserverMatches',p.Results.nObserverMatches,'nBelowThreshold',...
    p.Results.nBelowThreshold,'thresholdScaleFactor',...
    p.Results.thresholdScaleFactor,'noiseScaleFactor',noiseScaleFactor,...
    'LMEqualOD',false,'dlens0',true,'dmac0',true,'restrictBySd',true,...
    'makeAllObserverPlots',false,'sampledObservers',sampledConeParams);

%% QUEST+
[~,recoveredQuestParams,fittedQuestParams] = ...
    qpRayleighSim(subjID,nObservers,nQuestTrials,baseConeParams,...
    coneParamsToVary,noiseScaleFactor,p1Wl,p2Wl,testWls,'precomputeQuest',...
    p.Results.precomputeQuest,'age',p.Results.age,'fieldSize',...
    p.Results.fieldSize,'opponentParams',p.Results.opponentParams,...
    'p1Scale',p.Results.p1Scale,'p2Scale',p.Results.p2Scale,'testScale',...
    p.Results.testScale,'lambdaRef',p.Results.lambdaRef,'S',p.Results.S,...
    'plotAll',false,'plotLast',false,'sampledObservers',sampledConeParams);

%% Analyze results
% Calculate error associated with recovered parameters
coneErrStaircase = zeros(1,nObservers);
coneErrQuest = zeros(1,nObservers);
coneErrStd = zeros(1,nObservers);
for i = 1:nObservers
    coneErrStaircase(i) = findConeSensitivityError(sampledConeParams(i,:),...
        recoveredStaircaseParams(i,:),'age',p.Results.age,'fieldSize',...
        p.Results.fieldSize,'opponentParams',p.Results.opponentParams,'S',...
        p.Results.S);
    coneErrQuest(i) = findConeSensitivityError(sampledConeParams(i,:),...
        fittedQuestParams(i,:),'age',p.Results.age,'fieldSize',...
        p.Results.fieldSize,'opponentParams',p.Results.opponentParams,'S',...
        p.Results.S);
    coneErrStd(i) = findConeSensitivityError(sampledConeParams(i,:),...
        baseConeParams,'age',p.Results.age,'fieldSize',...
        p.Results.fieldSize,'opponentParams',p.Results.opponentParams,'S',...
        p.Results.S);
end

% Make bar graph of cone errors 
figure(); clf;
hold on;
bar([coneErrStaircase' coneErrQuest' coneErrStd']);
title('Cone Spectral Sensitivity Error');
legend('Simulated vs Staircase Params','Simulated vs QUEST+ Params',...
    'Simulated vs Standard Params');
ylabel('Error');
xlabel('Observer');

% Save results
save(outputFile,'coneErrStaircase','coneErrQuest','coneErrStd','subjID','p1Wl',...
    'p2Wl','testWls','baseConeParams','coneParamsToVary','nObservers',...
    'nQuestTrials','method','noiseScaleFactor','recoveredStaircaseParams',...
    'recoveredQuestParams','fittedQuestParams');
end